google/emboss

compiler/back_end/cpp/generated_code_templates, compiler/back_end/cpp/testcode/auto_array_size_test.cc, compiler/back_end/cpp/testcode/bcd_test.cc, compiler/back_end/cpp/testcode/bits_test.cc, compiler/back_end/cpp/testcode/condition_test.cc, compiler/back_end/cpp/testcode/dynamic_size_test.cc, compiler/back_end/cpp/testcode/enum_test.cc, compiler/back_end/cpp/testcode/requires_test.cc, compiler/back_end/cpp/testcode/virtual_field_test.cc, runtime/cpp/emboss_defines.h, runtime/cpp/emboss_enum_view.h, runtime/cpp/emboss_prelude.h, runtime/cpp/emboss_text_util.h, runtime/cpp/test/emboss_array_view_test.cc, runtime/cpp/test/emboss_constant_view_test.cc, runtime/cpp/test/emboss_defines_test.cc, runtime/cpp/test/emboss_enum_view_test.cc, runtime/cpp/test/emboss_maybe_test.cc, runtime/cpp/test/emboss_memory_util_test.cc, runtime/cpp/test/emboss_prelude_test.cc
Move all side-effectful operations outside of EMBOSS_CHECK and related macros.
Add EMBOSS_CHECK_ABORTS and EMBOSS_DCHECK_ABORTS macros, so that tests can enable/disable EXPECT_DEATH.
=> Fix bazel test -c opt ...:all

compiler/back_end/cpp/generated_code_templates, runtime/cpp/emboss_constant_view.h, runtime/cpp/test/emboss_memory_util_test.cc
constexpr non-static methods -> constexpr const non-static methods
Hide string_view behind C++17 check, not C++14.
=> Fix Emboss under C++14

compiler/back_end/cpp/header_generator.py
Temporary measure for customers who are still using Emboss under Python 2.
Also fix a couple of minor lint errors introduced by the same pull request that broke Python 2.
=> Make Emboss work under Python 2 again.

compiler/back_end/cpp/testcode/text_format_test.cc
Add test demonstrating that UpdateFromText() only updates fields provided in the text format.
=> Add additional test for UpdateFromText()

compiler/front_end/expression_bounds.py
Replace usage of fractions.gcd with a conditional that uses math.gcd if
it is available and which falls back to fractions.gcd if it is not. This
allows the code to work in Python 3.9+ where the deprecated
fractions.gcd function was removed.
If support for versions of Python older than 3.5 is dropped then this
code could be simplified to just use math.gcd.
=> Use math.gcd or fractions.gcd depending on what is available

compiler/back_end/cpp/generated_code_templates, compiler/back_end/cpp/testcode/condition_test.cc, compiler/back_end/cpp/testcode/requires_test.cc, doc/cpp-reference.md, runtime/cpp/emboss_array_view.h, runtime/cpp/emboss_enum_view.h, runtime/cpp/emboss_prelude.h, runtime/cpp/emboss_text_util.h, runtime/cpp/test/emboss_text_util_test.cc, testdata/requires.emb
Adds a new `WithAllowPartialOutput()` method to `TextOutputOptions` to
allow `WriteToString()` to write partial output when called with a
non-`Ok()` view.
=> Add a new option to allow partial text output for non-Ok() messages.

runtime/cpp/emboss_text_util.h
The line in question generates a compilation failure in Fuchsia, "error: implicit conversion loses integer precision: int to ::std::uint8_t" due to the "-Wimplicit-int-conversion" diagnostic flag. Adding an explicit `static_cast` here allows compilation.
=> Explicitly downcast in emboss_text_util.h

compiler/back_end/cpp/testcode/uint_sizes_test.cc
The `CanWriteExplicitlySizedEnumSizes` test can fail on some
compilers/configurations due to `buffer` being uninitialized.
This change fixes that issue.
=> Fix uninitialized memory in test code.

.github/scripts/set_release_version.py, .github/workflows/release.yml
Sets up a github workflow that will automatically push a release when the master branch is updated.
The release version is set by `set_release_version.py` and follows the format `YYYY.MMDD.HHMMSS`.
This release action doesn't do anything special at the moment except for creating a zipfile with the sources.  I plan to use this workflow as a basis for adding Arduino integration in the future.
=> Create automatic releases via github workflow.

runtime/cpp/emboss_text_util.h
The `TextOutputOptions::numeric_base_` field is stored as a `uint8_t`. However, `TextOutputOptions::WithNumericBase` takes an `int` parameter. Albeit unlikely, this allows for some potential data loss since an `int` on most systems is four bytes whereas a `uint8_t` is only a single byte.
A previous commit (85f3b790) used `static_cast` to remove the `-Wimplicit-int-conversion` compiler warning. However, we don't actually need a static cast here. Instead, we should just update the parameter type to be `uint8_t` since that's the type used in internal storage as well. It's unlikely that anyone will want a numeric base larger than 255 anyway, but if they do, they should deal with that at the call site rather than Emboss deciding to eliminate data under the hood.
This change updates …
=> runtime: TextOutputOptions::WithNumericBase should take a uint8_t

embossc
This shebang provides more general cross-platform portability and may fix a Fuchsia CQ build error
=> Generalize embossc shebang

runtime/cpp/emboss_prelude.h
This fixes implicit conversion errors in Fuchsia when compiling UIntView.
=> Fix implicit conversions in UIntView

compiler/util/traverse_ir.py
inspect.getargspec is no longer available in Python 3.11. Here are the docs as of 3.10:
https://docs.python.org/3.10/library/inspect.html#inspect.getargspec
This switches to getfullargspec which is nearly a drop in replacement: https://docs.python.org/3.11/library/inspect.html#inspect.getfullargspec
=> Fix Python 3.11 inspect usage

build_defs.bzl, compiler/back_end/cpp/BUILD, compiler/back_end/cpp/emboss_codegen_cpp.py, compiler/back_end/cpp/testcode/importer2_test.cc, compiler/front_end/emboss_front_end.py, testdata/BUILD, testdata/importer2.emb
This change creates the `emboss_library` and `cc_emboss_library` Starlark rules, which mirror `proto_library` and `cc_proto_library`.
This also fixes issues with `.emb` files that import `.emb` files that import `.emb` files, where imports-of-imports were not always included in the compilation.
This also required new command-line arguments to `emboss_front_end` (`--output-file`) and `emboss_codegen_cpp` (`--input-file` and `--output-file`).
=> Switch `emboss_cc_library` to use real Starlark rules.

compiler/front_end/attribute_checker_test.py, compiler/front_end/format_emb.py, compiler/front_end/format_emb_test.py, compiler/front_end/module_ir.py, compiler/front_end/module_ir_test.py, compiler/util/attribute_util.py, compiler/util/ir_pb2.py, doc/grammar.md, testdata/format/enum_value_attributes.emb, testdata/format/enum_value_attributes.emb.formatted, testdata/format/enum_value_attributes.emb.formatted_indent_4
As of this change, the grammar allows attributes on enum values, either inline or indented in the body, the same as fields. Additionally, this change updates the formatter and grammar documentation to account for this change.
=> Add attributes to enum values

compiler/back_end/cpp/BUILD, compiler/back_end/cpp/attributes.py, compiler/back_end/cpp/generated_code_templates, compiler/back_end/cpp/header_generator.py, compiler/back_end/cpp/header_generator_test.py, compiler/back_end/cpp/testcode/enum_case_test.cc, compiler/front_end/attribute_checker.py, compiler/util/attribute_util.py, compiler/util/name_conversion.py, compiler/util/name_conversion_test.py, doc/design_docs/archive/alternate_enum_cases.md, doc/language-reference.md, testdata/BUILD, testdata/enum_case.emb
Implements the `enum_case` attribute in the C++ backend to support emitting enum values with a case other than SHOUTY_CASE. Currently only the original SHOUTY_CASE and the new kCamelCase cases are supported, but adding a new case should be trivial.
Additionally, the implementation was designed to make it simple for a `name` attribute to be added for enum values (other IR nodes should be unaffected, it would be neither simpler nor harder to implement after this commit for other nodes).
Tests were added for case conversions, header generation, and a cc_test. All tests pass both in `bazel test` and `python -m unittest`.
A small change was made to the front-end, as some attribute handling functions were hoisted into `compiler/util` for reuse in the backend.
=> Implement `enum_case` attribute in cpp backend

compiler/back_end/cpp/header_generator.py, compiler/back_end/cpp/header_generator_test.py
Prior to this PR, an incorrectly-formatted namespace will fail an assert and print a python exception to the user. While this likely sufficient for a user to diagnose the issue, it is inconsistent with other error reporting in Emboss.
With this change, the namespace checking is implemented in the same way as other validations in the Emboss compiler, providing a specific file, line, and column range of the issue and printing the line containing the issue to the user.
=> Emit compilation errors for bad C++ namespaces

compiler/back_end/cpp/generated_code_templates
Disable all clang-tidy linting in C++ the body of the C++ outline template. This fixes several readability lint errors downstream.
=> Disable clang-tidy lint in C++ header body

compiler/back_end/cpp/attributes.py
The changes in PR #89 inadvertently added a line that is incompatible with Python version 3.8. However, Python 3.8 is still supported for around one more year from now (https://devguide.python.org/versions/), so this change restores 3.8 compatibility.
=> Fix subscripted types for Python 3.8

doc/language-reference.md
I also moved some documentation around to make bits and struct follow roughly the same order.
=> Reorder sections in bits to match the ordering in struct

build_defs.bzl
Add `toolchains` parameter to _cc_emboss_aspect rule to fix find_cpp_toolchain error.
Fixes #103
=> Fix emboss_cpp_library Bazel rule

build_defs.bzl
Move cpp_utils from the cc_common.compile private_hdrs parameter to the compilation_contexts parameter in order to fix the cpp_utils header include paths when Emboss is an external repository.
Fixes #108
=> Move cpp_utils to compilation_contexts

compiler/back_end/cpp/BUILD, compiler/back_end/cpp/header_generator.py, compiler/front_end/BUILD, compiler/front_end/constraints.py, compiler/front_end/glue.py, compiler/front_end/parser.py, compiler/util/BUILD, compiler/util/resources.py
For loading resources, use `importlib.resources.files()` instead of `pkgutil.get_data()`.  This works across project boundaries with Bazel 7, as well as through the `embossc` driver.
Also packaged resource loading into a utility function, so that further changes can be more easily accomodated.
=> Switch from pkgutil to importlib.resources.

build_defs.bzl, testdata/BUILD, testdata/import_dir/project/imported.emb, testdata/import_dir/project/importer.emb
`import_dirs` arguments come through as part of the `ctx.files` list and need to have their `path` extracted when building the `embossc` command-line. This CL also adds a `testdata` entry that checks that `emboss_cc_library` works when specifying `import_dirs`.
Test: `bazel build //testdata:import_dir_importer_emboss`
=> Fix `import_dirs` support

compiler/front_end/constraints.py, compiler/front_end/symbol_resolver.py, compiler/util/traverse_ir.py
Fixes issue #119.
1. In preparation for a perf improvement all actions that use lambdas are converted to static functions. Additionally duplicate actions are removed.
2. The results of `getfullargspec` are memoized and encapsulated in a helper class.
This gets us from 100K calls to `getfullargspec` to about 60 and reduces overhead from 10% to ~0% in my tests.
=> Improve perf of `_call_with_optional_args`

.bazelrc, runtime/cpp/test/emboss_memory_util_test.cc
These allocator members were deprecated in C++17 and deleted in C++20.
This upstreams cl/601574967.
=> Remove references to deprecated allocator members

runtime/cpp/test/emboss_memory_util_test.cc
std::basic_string<unsigned char> relies on a non-standard generic char_traits<> implementation, recently removed from libc++.
Upstreams cl/605337651.
Relevant to #116.
=> Stop using std::basic_string<unsigned char>

compiler/back_end/cpp/emboss_codegen_cpp.py, compiler/front_end/emboss_front_end.py, embossc
Rather than spawning 2 subprocesses and serializing IR data between them
we can just use the front end and back end libraries directly. This is a
code simplification as well as a performance improvement showing up a 3%
reduction in overhead for larger emb files.
Fixes #122.
=> Call parsing and generation functions directly in `embossc`

WORKSPACE, compiler/back_end/cpp/BUILD, compiler/back_end/util/BUILD, compiler/front_end/BUILD, compiler/util/BUILD, doc/BUILD, integration/googletest/BUILD, runtime/cpp/test/BUILD, testdata/BUILD
This adds an explicit dependency on rules_python and loads py_library and py_binary rules from there, instead of relying on built-in versions in Bazel.
Doing so prepares us for the rollout of
https://github.com/bazelbuild/bazel/issues/15897 (which is happening internally already, and across the Bazel ecosystem soon).
Except for the change to the WORKSPACE file, this change was auto-generated by running,
buildozer 'new_load @rules_python//python:py_library.bzl py_library' //...:__pkg__
buildozer 'new_load @rules_python//python:py_binary.bzl py_binary' //...:__pkg__
buildozer 'new_load @rules_python//python:py_test.bzl py_test' //...:__pkg__
buildozer 'fix unusedLoads' //...:__pkg__
Upstreams cl/551628592.
=> Load py_library, py_binary from rules_python

compiler/back_end/cpp/header_generator.py, compiler/front_end/attribute_checker.py, compiler/front_end/attribute_checker_test.py, compiler/front_end/constraints.py, compiler/front_end/expression_bounds.py, compiler/front_end/module_ir.py, compiler/front_end/synthetics.py, compiler/front_end/synthetics_test.py, compiler/front_end/type_check.py, compiler/front_end/write_inference.py, compiler/front_end/write_inference_test.py, compiler/util/attribute_util.py, compiler/util/ir_pb2.py, compiler/util/ir_util.py, compiler/util/ir_util_test.py
Adds `FunctionMapping` and `AddressableUnit` enums and pulls out the existing definitions from the IR classes. This is in preparation for #118.
=> Split out IR enums

.gitignore, MODULE.bazel
Some versions of `bazel` have started generating a `MODULE.bazel` file
in preparation for the migration to `bzlmod`. This adds the default file
for now and updates `.gitignore` to ignore the associated lock file.
=> Add a default MODULE.bazel

build_defs.bzl, compiler/back_end/cpp/BUILD, compiler/back_end/cpp/emboss_codegen_cpp.py, compiler/back_end/cpp/generated_code_templates, compiler/back_end/cpp/header_generator.py, compiler/back_end/cpp/testcode/no_enum_traits_test.cc, embossc, runtime/cpp/emboss_array_view.h, runtime/cpp/emboss_cpp_util.h, runtime/cpp/emboss_enum_view.h, runtime/cpp/emboss_prelude.h, runtime/cpp/emboss_text_util.h, runtime/cpp/test/emboss_array_view_test.cc, runtime/cpp/test/emboss_cpp_util_google_integration_test.cc, runtime/cpp/test/emboss_enum_view_test.cc, runtime/cpp/test/emboss_memory_util_test.cc, runtime/cpp/test/emboss_prelude_test.cc, testdata/BUILD, testdata/no_enum_traits.emb
This change makes the generation of EnumTraits configurable. With this
change we can see reductions in code size by over 1MB. Example file
size changes:
|File              | src (KB) | .h (KB) before | .h (KB) after |
|------------------|----------|----------------|---------------|
| hci_events.emb   |       76 |           5356 |          3884 |
| hci_commands.emb |      108 |           5612 |          4268 |
| hci_vendor.emb   |       32 |           1748 |          1304 |
| hci_common.emb   |       32 |            644 |           368 |
| hci_data.emb     |        4 |            152 |           104 |
| l2cap_frames.emb |        4 |             48 |            40 |
| hci_h4.emb       |        4 |              8 |             4 |
This is also helpful for embedded users who couldn't use …
=> Split out enum trait generation

compiler/back_end/cpp/emboss_codegen_cpp.py, compiler/front_end/emboss_front_end.py, compiler/front_end/glue.py, compiler/front_end/glue_test.py, compiler/front_end/module_ir_test.py, compiler/front_end/type_check_test.py, compiler/util/BUILD, compiler/util/ir_data_utils.py, compiler/util/ir_util_test.py, compiler/util/traverse_ir_test.py
In preparation for reworking `ir_data` move json serialazition to it's own class. For now this is simply a wrapper. All `to_json` call sites are updated.
Part of #118.
=> Split out an `IrDataSerializer` class

compiler/back_end/cpp/header_generator_test.py, compiler/front_end/expression_bounds.py, compiler/front_end/module_ir.py, compiler/front_end/symbol_resolver.py, compiler/front_end/synthetics.py, compiler/front_end/type_check.py, compiler/front_end/write_inference.py, compiler/util/ir_data_utils.py, compiler/util/ir_util_test.py
This adds an `ir_data_utils.builder` wrapper that will be used to dynamically build up `ir_data` instances rather than the ad-hoc behavior of `ir_data` field access. For now this is a no-op and simply annotates sites that are mutating `ir_data` instances.
Part of #118.
=> Add `ir_data_utils.builder`

compiler/back_end/cpp/header_generator.py, compiler/front_end/attribute_checker.py, compiler/front_end/constraints.py, compiler/front_end/expression_bounds.py, compiler/front_end/synthetics.py, compiler/front_end/type_check.py, compiler/front_end/write_inference.py, compiler/util/attribute_util.py, compiler/util/ir_data_utils.py, compiler/util/ir_util.py
This adds an `ir_data_utils.reader` wrapper that will be used to access potentially unset chains of fields in an `ir_data` instance. For now this is simply an annotation that marks sites that are accessing missing fields.
Part of #118.
=> Add `ir_data_utils.reader`

compiler/back_end/cpp/header_generator.py, compiler/front_end/glue.py, compiler/front_end/glue_test.py, compiler/front_end/module_ir.py, compiler/front_end/symbol_resolver.py, compiler/front_end/synthetics.py, compiler/util/attribute_util.py, compiler/util/ir_data_utils.py
This adds `ir_data_utils` helpers to handle copying and updating `ir_data` instances. Some instances of `CopyFrom` that aren't associated with a `builder` are updated to use `copy` or `update`.
Part of #118.
=> Add `ir_data_utils.copy` and `update`

runtime/cpp/emboss_arithmetic.h
Fix missing template parameters in MaybeDo. The latest version of clang throws an error without this fix.
=> Fix missing template parameters

compiler/back_end/cpp/generated_code_templates
`<ostream>` isn't needed unless enum traits are being used, in that case it will be included by the files that need it. Removing this fixes a failure for targets that don't have `<ostream>` available.
Fixes: #156
=> Remove unused <ostream>

build_defs.bzl, testdata/BUILD
Forwards kwargs to emboss_cc_library to fix https://github.com/google/emboss/issues/154.
=> Forward kwargs to emboss_cc_library

compiler/front_end/constraints_test.py, compiler/front_end/module_ir_test.py, compiler/front_end/symbol_resolver.py, compiler/front_end/synthetics.py, compiler/util/BUILD, compiler/util/error.py, compiler/util/ir_data.py, compiler/util/ir_data_fields.py, compiler/util/ir_data_fields_test.py, compiler/util/ir_data_utils.py, compiler/util/ir_data_utils_test.py, compiler/util/ir_util.py, compiler/util/test_util.py, compiler/util/traverse_ir.py
This converts `ir_data` over to a `dataclasses.dataclass` and adds various `FieldSpec` helpers to support that conversion. The `builder`, `reader`, `IrDataSerializer`, `copy`, and `update` stubs are fully implemented to support dataclasses as well.
This change results in a 38% speedup against a 75KB test file.
Fixes #118.
=> Convert `ir_data` to a `dataclass`

runtime/cpp/emboss_cpp_types.h, runtime/cpp/emboss_memory_util.h, runtime/cpp/test/emboss_cpp_types_test.cc, runtime/cpp/test/emboss_memory_util_test.cc
Renames `IsChar` to `IsAliasSafe`, removes `signed char` as an alias safe type and adds in conditional support for `std::byte` as an anlias safe type if available.
Fixes: #116
=> Update set of supported alias-safe types

compiler/front_end/module_ir_test.py
There are a couple negative compilation tests in `compiler/front_end/module_ir_test.py` named `anonymous bits does not allow documentation` and `anonymous bits does not allow subtypes`. These weren't being run because `_make_negative_tests()`wasn't being called.
=> Runs compilation failure tests.

.github/workflows/run-bazel-tests.yml
This will ensure that all pull requests must pass all Bazel tests in the repository. Merging the pull request will be blocked until the tests are passing, and will re-run each time the pull request is synchronized or updated.
=> Add Github action to run Bazel tests for every PR

compiler/util/ir_data_fields.py, compiler/util/ir_data_utils.py
Python 3.9 is still supported, but Python 3.9 does not support type unions with the `|` operator. This change removes these in favor of `Union[...]` or `Optional[...]` as appropriate.
Confirmed all tests pass using Python 3.9
=> Fix for Python 3.9

runtime/cpp/emboss_memory_util.h
Since code defines copy constructor it should also define the assignment operator (rule of three).
This also fixes #148.
=> Explicitly define default ContiguousBuffer assign op

build_defs.bzl
This is accomplished by allowing `visibility` to be picked up by `kwargs`.
=> Add `visibility` to the Bazel rule for the Emboss IR.

runtime/cpp/emboss_prelude.h
This allows using a larger backing value type to assign a UInt or Int value when the value itself fits within the range of the internal value type. Previously this would fail to compile if `-Wshorten-64-to-32` was specified when building with `clang`:
```
UIntView<FixedSizeViewParameters<16, AllValuesAreOk>> view;
size_t value = 200;
view.TryToWrite(value);
```
Fixes #185
=> Cast to ValueType before ValueIsOk check

compiler/front_end/lr1.py, compiler/front_end/lr1_test.py
With this change, the `Parser.action` and `.goto` tables are now 2-layer hash tables, using states as the keys for the outer tables and symbols as the keys for the inner tables.  Functionally, this means that `action[state, symbol]` becomes `action[state][symbol]`, and likewise for `goto`.
This also allows the `expected` table to be eliminated, as it can be quickly computed from `action[state]` when needed.
This goal of this change is to have a more compact representation for issue #193: by structuring the tables this way, state numbers do not need to be repeated in the serialized output.  Eliminating `expected` also provides a modest savings.  The total savings is approximately 55%, going from 4.3MB without this change to 1.9MB with this change.
=> Restructure ACTION and GOTO tables.

compiler/front_end/emboss_front_end.py, compiler/front_end/glue.py
This exposes the existing `stop_before_step` functionality that is used in unit tests through the command line, which allows the IR to be inspected/analyzed.
This is a pure debug option.
=> Add `--debug-stop-before-step` flag.

compiler/back_end/cpp/header_generator.py, compiler/front_end/attribute_checker.py, compiler/front_end/constraints.py, compiler/front_end/expression_bounds.py, compiler/front_end/expression_bounds_test.py, compiler/front_end/module_ir.py, compiler/front_end/symbol_resolver.py, compiler/front_end/symbol_resolver_test.py, compiler/front_end/type_check.py, compiler/front_end/type_check_test.py, compiler/front_end/write_inference.py, compiler/front_end/write_inference_test.py, compiler/util/attribute_util.py, compiler/util/ir_data.py, compiler/util/ir_data_fields.py, compiler/util/ir_data_fields_test.py, compiler/util/ir_data_utils.py, compiler/util/ir_util.py
This change refactors `OneOfField` so that all fields in a given `oneof`
construct share the same backing attributes on their container class --
`which_{oneof name}`, which holds the (string) name of the
currently-active member of the oneof named `{oneof name}` (or `None` if
no member is active), and `_value_{oneof name}`, which holds the value
of the currently-active member (or `None`).
This avoids looping through field specs in order to do an update or to
figure out which member of a `oneof` is currently active.
Since the `WhichOneof()` method is now a trivial read of a
similarly-named attribute, it can be inlined for a small decrease in
overall code size and without sacrificing readability.
As a result of these changes, the compiler now runs 4.5% faster on my
large test `.emb`.
=> Replace `WhichOneof("x")` with `which_x`. 

compiler/front_end/emboss_front_end.py, compiler/front_end/parser.py, compiler/util/error.py, compiler/util/error_test.py
This change checks to see if the cached parser was discarded due to a mismatch between the cached parser and the grammar specified in module_ir.py, and, if so, emits a warning that the cached parser was not used, along with informational messages on the nature of the mismatch.
Adjusted the "warning" color from magenta to yellow.  (This is the first warning in Emboss, so no magenta messages would have ever been emitted.)
Adjusted the "note" color from "bright black" (dark grey) to "white" (light grey), becaused at least some terminals display "bright black" as just black.
=> Emit a warning when the cached parser is not used.

compiler/back_end/cpp/header_generator.py, compiler/back_end/cpp/header_generator_test.py, compiler/front_end/glue.py, compiler/front_end/glue_test.py, compiler/front_end/lr1.py, compiler/front_end/lr1_test.py, compiler/front_end/module_ir.py, compiler/front_end/module_ir_test.py, compiler/front_end/symbol_resolver.py, compiler/front_end/synthetics.py, compiler/front_end/tokenizer.py, compiler/front_end/tokenizer_test.py, compiler/front_end/write_inference.py, compiler/util/BUILD, compiler/util/error.py, compiler/util/error_test.py, compiler/util/ir_data.py, compiler/util/ir_data_fields_test.py, compiler/util/ir_data_utils.py, compiler/util/ir_data_utils_test.py, compiler/util/ir_util_test.py, compiler/util/parser_types.py, compiler/util/parser_types_test.py, compiler/util/test_util.py, compiler/util/test_util_test.py, compiler/util/traverse_ir.py, testdata/golden/span_se_log_file_status.ir.txt, testdata/golden/span_se_log_file_status.parse_tree.txt, testdata/golden/span_se_log_file_status.tokens.txt
This change makes the `Location` dataclass, which does not change
frequently, into a new `SourceLocation` namedtuple, and changes the
`SourceLocation` serialization.  As a result, with this change:
*   `embossc` runs about 25% faster on a large (7kLOC) input; `python3
-OO embossc` runs about 19% faster on the same input.
*   Serialized IR is about 45% smaller.
Details:
*   Replace the `ir_data.Location` dataclass with a new
`parser_types.SourceLocation` namedtuple.  The rename helps clarify
the difference between a location within source code
(`SourceLocation`) and a location within a structure
(`FieldLocation`).
*   Similarly, replace `ir_data.Position` with
`parser_types.SourcePosition`.
*   Update any place that edits a `SourceLocation` with an appropriate
assignment; e.g., …
=> Convert Location to a namedtuple, and associated cleanup

.github/workflows/verify-pull-request.yml, runtime/cpp/emboss_defines.h, runtime/cpp/emboss_memory_util.h
With certain versions of GCC, `bazel test -c opt ...` failed, apparently due to a compiler bug.
This change:
1.  Adds a workaround for the GCC bug.
2.  Enables the workaround on versions of GCC known to have the bug.
3.  Documents the bug (in comments).
4.  Enables testing with `-c opt` as part of the commit hook.
Note that the versions covered by #2 are a little wider than may be technically necessary.  As of the time of writing, this affects all released versions of GCC from 12.1 through 14.1, but the GCC fix has been backported to the 12.X and 13.X branches.  It may be possible to reduce the workaround's scope once those are released.
=> Fix tests under `bazel test -c opt`.

compiler/front_end/constraints.py, compiler/front_end/constraints_test.py, compiler/front_end/expression_bounds.py, compiler/front_end/glue.py
Prior to this change, if a user omitted the length of an integer parameter *and* used that parameter as an argument to an operator or function, the compiler with throw an `AttributeError` instead of providing a useful message.
This is because the check that integer runtime parameters have an explicit size happened later than the function in `expression_bounds.py` that tried to use the size.
This change moves the check earlier (incidentally spliting `check_constraints` into `check_constraints` and
`check_early_constraints`), and also gives it a better error message.
=> Add error message for obscure case with parameters.

.github/workflows/verify-pull-request.yml, compiler/back_end/cpp/testcode/auto_array_size_test.cc
This fixes the `clang` test failures.
Also update workflow to emit test logs on failure.
=> Add `alignas` specifier to buffer in explicit alignment test.
